apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: quarkus-test-result
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-test-result 
  name: quarkus-test-result
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: quarkus-test-result
    weight: 100 
