apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: quarkus-test-result
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-test-result 
  name: quarkus-test-result
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: quarkus-test-result 
